### ISSUE TITLE
Consolidation on board representation

### ISSUE THREAD

**Issue by RobertCochran** [RobertCochran/connect4#1]
So, each of us is using a slightly different set of strings to represent the
internals of the board. We really ought to figure out a common set.

I recommend to use 'r' and 'b' for the checkers, since 2 of the 3 of us are
using them. This is hopefully straight forward.

The hard part is going to be determining a blank space. I've chosen to use `.`
in my code, @Abananiac has chosen ` `, and @13YannBoat initially chose`.`as
well but changed to`_`. According to the commit log, 754d4a34, the first commit
with actual code, uses`.` as the blank space representation.

I prefer `.` as it is an actual printing character that does not blend with
itself, making it easily countable in raw board printouts.

Thoughts?

(Note: this does not affect the representation of the board in the display code. The
display code can do whatever it feels like doing.)

**Comment by pavlenko-yann** [comment]
OK, i guess I should change to the  "."  or leave as is "_" ?

**Comment by RobertCochran** [comment]
I think @Abananiac should weigh in before we make a final decision, but I'd prefer the `.`.
Let's wait until we agree on something, so we don't have to change it multiple times.

**Comment by Abananiac** [comment]
I think I would prefer using [.] instead of using "_".

**Comment by RobertCochran** [comment]
Then I believe we have consensus as follows:

```
Red Token == 'r'
Black Token == 'b'
Empty Space == '.'
```

Sound right?

**Comment by Abananiac** [comment]
Yea, that sounds right.

**Comment by pavlenko-yann** [comment]
Yea, that sounds right.

**Comment by RobertCochran** [comment]
Excellent. Could we all whip up patches for our parts?

**Comment by Abananiac** [comment]
What do you mean by "whip up patches"?

**Comment by RobertCochran** [comment]
Just making those changes in the different modules;
changing board.py and user_input.py to comply with our agreement.

**Comment by Abananiac** [comment]
I changed the blank space to a '.' in the user_input.py, I already had the 'r' and 'b' in lowercase letters.

**Comment by pavlenko-yann** [comment]
I changed the '_' to a '.' in the board.py, and lower cased the 'R' to 'r' and 'B' to 'b'.

**Comment by RobertCochran** [comment]
Unity achieved in 8de819b4 and fdfe6988.
Thanks!
